### ISSUE TITLE
any demo or detailed document?

### ISSUE THREAD

**Issue by shanhuiyang** [utsrapido/react-rte-semantic#1]
any demo or detailed document?

**Comment by DrTerr** [comment]
Please have a look at: https://github.com/sstur/react-rte
This is largely based on react-rte, with custom components like buttons being replaced with semantic components.
Feel free to clone repo and build it with yarn/npm, it have an example page. It will be built and you can experiment with it.
For documentation I might rewrite part of it in to typescript, this way interfaces are way easier to browse.

**Comment by shanhuiyang** [comment]
Thanks, indeed react-rte have little documents. And they have many bugs in its demo.

**Comment by shanhuiyang** [comment]
By the way, do you have any plan to rebase the latest branch from react-rte?

**Comment by DrTerr** [comment]
They haven't added much yet, and some of UI bugs have been fixed after replacing components with semantics'.
I am waiting on major changes in draft.js before considering an upgrade.
Mobile view for example is still doesn't function in draft.js it self, and not related to this or sstur's editor.
Also some of my changes not directly compatible, as such I cannot rebase easily.
Though feel free rebase to incorporate some changes from react-rte and submit a pull request.
